main: me.Skimm.chatCommands.Main
name: chatEmotes
version: 0.4.3
author: Skimm
commands:
  emote:
    description: Use /emote help to see command list
  broadcast:
    description: Use /broadcast help to see command list
  mod:
    description: Use /mod help to see command list
  chat:
    description: Use /chat help to see command list
    aliases: [region, r, all, a, shout, s, whisper, w, group, g, party, p, local, l]
  title:
    description: Use /title help to see command list